# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Modelcode.py
# Created on: 2018-01-23 16:00:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Modelcode <Input_Features> <Layer> <Intersect_shp> <Distance__value_or_field_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Features = arcpy.GetParameterAsText(0)

Layer = arcpy.GetParameterAsText(1)

Intersect_shp = arcpy.GetParameterAsText(2)
if Intersect_shp == '#' or not Intersect_shp:
    Intersect_shp = "M:\\Documents\\PRO2\\Intersect.shp" # provide a default value if unspecified

Distance__value_or_field_ = arcpy.GetParameterAsText(3)

# Local variables:
Output_Feature_Class = "M:\\Documents\\PRO2\\buffer.shp"

# Process: Buffer
arcpy.Buffer_analysis(Input_Features, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "PLANAR")


# Process: Intersect
arcpy.Intersect_analysis([Layer,Output_Feature_Class], Intersect_shp, "ALL", "", "INPUT")

